export const dict = {
    en: {
        login: "Log in",
        password: "Password",
        signUp: "Sign up",
        passwordError: "Wrong password, try again.",
        logout: "Log out",
        canvas: "Canvas",
        clear: "Clear",
        color: "Color",
        size: "Size",
        eraser: "Eraser",
        undo: "Undo",
        save: "Save",
        createroom: "Create room",
        joinroom: "Join room",
        roomname: "Room name",
        desc: "Description",
        adduser: "Add user",
        add: "Add",
        create: "Create",
        cancel: "Cancel",
        room: "Room",
        join: "Join",
        welcome: "Welcome to CommonRoom!",
        email: "Email",
        username: "Username",
        login: "Log in",
        logout: "Log out",
        signup: "Sign up",
        lobbytext: "Create room or join to existing room",
        changeusername: "Change username",
        update: "Update",
        chattitle: "Chat in room: ",
        shuffle: "Shuffle",
        settings: "Settings",
        width: "Width",
        height: "Height",
        apply: "Apply",
        alertfill: "Please fill in all fields",
        alertroomexists: "Room already exists",
        alertroomdoesntexist: "Room doesn't exist",
        roomcreated: "Room created successfully",
        errorcreatingroom: "Error creating room",
        shufflesettings: "Shuffle settings",
        norounds: "Number of rounds",
        mode: "Mode",
        shufflemode1: "Picture first",
        shufflemode2: "Text first",
        players: "Players",
        leave: "Leave",
        start: "Start",
        ready: "Ready",
        round: "Round",
    },
    pl: {
        login: "Zaloguj się",
        password: "Hasło",
        signUp: "Zarejestruj się",
        passwordError: "Błędne hasło, spróbuj ponownie.",
        logout: "Wyloguj się",
        canvas: "Tablica",
        clear: "Wyczyść",
        color: "Kolor",
        size: "Rozmiar",
        eraser: "Gumka",  
        undo: "Cofnij",
        save: "Zapisz",
        createroom: "Stwórz pokój",
        joinroom: "Dołącz do pokoju",
        roomname: "Nazwa pokoju",
        desc: "Opis",
        adduser: "Dodaj użytkownika",
        add: "Dodaj",
        create: "Stwórz",
        cancel: "Anuluj",
        room: "Pokój",
        join: "Dołącz",
        welcome: "Witaj w CommonRoom!",
        email: "Email",
        username: "Nazwa użytkownika",
        login: "Zaloguj się",
        logout: "Wyloguj się",
        signup: "Zarejestruj się",
        lobbytext: "Stwórz pokój lub dołącz do istniejącego",
        changeusername: "Zmień nazwę użytkownika",
        update: "Zaktualizuj",
        chattitle: "Czat w pokoju: ",
        shuffle: "Podaj dalej",
        settings: "Ustawienia",
        width: "Szerokość",
        height: "Wysokość",
        apply: "Zastosuj",
        alertfill: "Proszę wypełnić wszystkie pola",
        alertroomexists: "Pokój już istnieje",
        alertroomdoesntexist: "Pokój nie istnieje",
        roomcreated: "Pokój został utworzony",
        errorcreatingroom: "Błąd podczas tworzenia pokoju",
        shufflesettings: "Ustawienia Podaj Dalej",
        norounds: "Liczba rund",
        mode: "Tryb",
        shufflemode1: "Obrazek pierwszy",
        shufflemode2: "Tekst pierwszy",
        players: "Gracze",
        leave: "Wyjdź",
        start: "Start",
        ready: "Gotowy",
        round: "Runda",
    }
};
