export const dict = {
    en: {
        login: "Log in",
        password: "Password",
        signUp: "Sign up",
        passwordError: "Wrong password, try again.",
        logout: "Log out",
        canvas: "Canvas",
        clear: "Clear",
        color: "Color",
        size: "Size",
        eraser: "Eraser",
        undo: "Undo",
        save: "Save",
        createroom: "Create room",
        roomname: "Room name",
        desc: "Description",
        adduser: "Add user",
        add: "Add",
        create: "Create",
        cancel: "Cancel",
        room: "Room",
        join: "Join"
    },
    pl: {
        login: "Zaloguj się",
        password: "Hasło",
        signUp: "Zarejestruj się",
        passwordError: "Błędne hasło, spróbuj ponownie.",
        logout: "Wyloguj się",
        canvas: "Płótno",
        clear: "Wyczyść",
        color: "Kolor",
        size: "Rozmiar",
        eraser: "Gumka",  
        undo: "Cofnij",
        save: "Zapisz",
        createroom: "Stwórz pokój",
        roomname: "Nazwa pokoju",
        desc: "Opis",
        adduser: "Dodaj użytkownika",
        add: "Dodaj",
        create: "Stwórz",
        cancel: "Anuluj",
        room: "Pokój",
        join: "Dołącz"
    }
};
