export const dict = {
    en: {
        login: "Log in",
        password: "Password",
        signUp: "Sign up",
        passwordError: "Wrong password, try again.",
        logout: "Log out",
        canvas: "Canvas",
        clear: "Clear",
        color: "Color",
        size: "Size",
        eraser: "Eraser",
        undo: "Undo",
        save: "Save",
        createroom: "Create room",
        joinroom: "Join room",
        roomname: "Room name",
        desc: "Description",
        adduser: "Add user",
        add: "Add",
        create: "Create",
        cancel: "Cancel",
        room: "Room",
        join: "Join",
        welcome: "Welcome to CommonRoom!",
        email: "Email",
        username: "Username",
        login: "Log in",
        logout: "Log out",
        signup: "Sign up",
        lobbytext: "Create room or join to existing room",
        changeusername: "Change username",
        changepic: "Change avatar",
        update: "Update",
        chattitle: "Chat in room: ",
        shuffle: "Shuffle",
        settings: "Settings",
        width: "Width",
        height: "Height",
        apply: "Apply",
        alertfill: "Please fill in all fields",
        alertroomexists: "Room already exists",
        alertroomdoesntexist: "Room doesn't exist",
        roomcreated: "Room created successfully",
        errorcreatingroom: "Error creating room",
        shufflesettings: "Shuffle settings",
        norounds: "Number of rounds",
        mode: "Mode",
        shufflemode1: "Picture first",
        shufflemode2: "Text first",
        players: "Players",
        leave: "Leave",
        start: "Start",
        ready: "Ready",
        round: "Round",
        waiting: "Waiting for all players...",
        picture: "'s picture:",
        text: "'s text:",
        finishandreturn: "Finish and return to menu",
        errorloadinground: "Error loading round (data may have been deleted)",
        gottadrawfast: "Gotta draw fast!",
        gottasettings: "Gotta draw fast! settings",
        roundtimemin: "Minimum drawing time",
        roundtimemax: "Maximum drawing time",
        drawingtime: "drawing time",
        gottaresults: "Processing results...",
        enterusername: "Please enter your username",
        usernamechanged: "Username changed",
        avatarchanged: "Avatar changed",
        notenoughplayers: "Not enough players",
        invalidnorounds: "Invalid number of rounds",
        invalidtime: "Invalid time",
        loggedin: "Logged in",
        loggedout: "Logged out",
        createdaccount: "Account created",
        errorcreatingaccount: "Error creating account",
        errorloggingin: "Error logging in",
    },
    pl: {
        login: "Zaloguj się",
        password: "Hasło",
        signUp: "Zarejestruj się",
        passwordError: "Błędne hasło, spróbuj ponownie.",
        logout: "Wyloguj się",
        canvas: "Tablica",
        clear: "Wyczyść",
        color: "Kolor",
        size: "Rozmiar",
        eraser: "Gumka",  
        undo: "Cofnij",
        save: "Zapisz",
        createroom: "Stwórz pokój",
        joinroom: "Dołącz do pokoju",
        roomname: "Nazwa pokoju",
        desc: "Opis",
        adduser: "Dodaj użytkownika",
        add: "Dodaj",
        create: "Stwórz",
        cancel: "Anuluj",
        room: "Pokój",
        join: "Dołącz",
        welcome: "Witaj w CommonRoom!",
        email: "Email",
        username: "Nazwa użytkownika",
        login: "Zaloguj się",
        logout: "Wyloguj się",
        signup: "Zarejestruj się",
        lobbytext: "Stwórz pokój lub dołącz do istniejącego",
        changeusername: "Zmień nazwę użytkownika",
        changepic: "Zmień avatar",
        update: "Zaktualizuj",
        chattitle: "Czat w pokoju: ",
        shuffle: "Podaj dalej",
        settings: "Ustawienia",
        width: "Szerokość",
        height: "Wysokość",
        apply: "Zastosuj",
        alertfill: "Proszę wypełnić wszystkie pola",
        alertroomexists: "Pokój już istnieje",
        alertroomdoesntexist: "Pokój nie istnieje",
        roomcreated: "Pokój został utworzony",
        errorcreatingroom: "Błąd podczas tworzenia pokoju",
        shufflesettings: "Ustawienia Podaj Dalej",
        norounds: "Liczba rund",
        mode: "Tryb",
        shufflemode1: "Obrazek pierwszy",
        shufflemode2: "Tekst pierwszy",
        players: "Gracze",
        leave: "Wyjdź",
        start: "Start",
        ready: "Gotowy",
        round: "Runda",
        waiting: "Oczekiwanie na wszystkich graczy...",
        picture: " narysował obrazek:",
        text: " napisał tekst:",
        finishandreturn: "Zakończ i wróć do menu",
        errorloadinground: "Błąd podczas ładowania rundy (możliwe, że dane zostały usunięte)",
        gottadrawfast: "Kto pierwszy ten lepszy", 
        gottasettings: "Musisz rysować szybko! ustawienia",
        roundtimemin: "Minimalny czas rysowania",
        roundtimemax: "Maksymalny czas rysowania",
        drawingtime: "czas rysowania",
        gottaresults: "Przetwarzanie wyników...",
        enterusername: "Proszę podać nazwę użytkownika",
        usernamechanged: "Nazwa użytkownika została zmieniona",
        avatarchanged: "Avatar został zmieniony",
        notenoughplayers: "Za mało graczy",
        invalidnorounds: "Nieprawidłowa liczba rund",
        invalidtime: "Nieprawidłowy czas",
        loggedin: "Zalogowano",
        loggedout: "Wylogowano",
        createdaccount: "Konto zostało utworzone",
        errorcreatingaccount: "Błąd podczas tworzenia konta",
        errorloggingin: "Błąd podczas logowania",
    }
};
